--- 1.8
--- [a] -> a
--- (b, a) -> (a, b)
--- b -> a -> (b, a)
--- Num a => a -> a
--- Fractional a => a -> a
--- Char -> Bool
--- Ord a => a -> a -> a -> Bool
--- Eq a => [a] -> Bool
--- (a -> a) -> a -> a